/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as alloProtocol from "./allo-protocol";
export type { alloProtocol };
export type { DAIMock } from "./DAIMock";
